[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

[language-server.hx-lsp]
command = "/home/hv/.cargo/bin/hx-lsp"

[language-server.eslint]
command = "eslint"

[language-server.stylelint]
args = ["--stdin"]
command = "stylelint"

[[language]]
name = "html"
auto-format = true
language-servers = ["vscode-html-language-server", "stylelint", "emmet-ls", "eslint", "hx-lsp"]
